services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lms-app
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on: []

  web:
    image: nginx:1.27-alpine
    container_name: lms-web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  # Queue worker
  worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lms-worker
    command: sh -c "php artisan queue:work --queue=attachments,default --sleep=3 --tries=3"
    volumes:
      - .:/var/www/html
    depends_on:
      - app

  # Scheduler (runs 'schedule:run' every minute)
  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lms-scheduler
    command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    volumes:
      - .:/var/www/html
    depends_on:
      - app
  redis:
    container_name: lms-redis
    image: redis:7-alpine
    ports: ["6379:6379"]

  horizon:
    container_name: lms-horizon
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command: php artisan horizon
    depends_on: [app, redis]
    volumes:
      - .:/var/www/html
    env_file:
      - .env

  node:
    image: node:20-alpine
    container_name: lms-node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm ci && npm run dev"
    depends_on:
      - web
